### PR TITLE
fix: questionservice

### LINKED ISSUE #290: Fix QuestionService

### PR DESCRIPTION
**Pull request by Guekka**
Fix: #290

### CODE REVIEW

**Comment by Apoorva64** [comment]
# ☁️ Nx Cloud Report

> ⚠️ Important: This organization has reached the limit of the FREE Plan and will be disabled at the end of the month. Remote caching and distributed task execution will no longer work. Your CI may stop working.
        

CI is running/has finished running commands for commit 9a0e4f365a2b651a02a403a48883fceafac2c8ee. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=640ee8fb56da4d6500e89717&branchName=291,290-fix-questionservice)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`nx serve backend-api`](https://cloud.nx.app/runs/1d2Zn41DK4)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

**Review by Apoorva64 — CHANGES_REQUESTED** [review]
Seperate services question/clue/answer

**Comment by Guekka** [comment]
> Seperate services question/clue/answer

While that would be better, I think that's not important right now. We have far more important issues

**Review by Apoorva64 — APPROVED** [review]
can do better

**Pull request merged**
