### PR TITLE
change quiz title and image

### PR DESCRIPTION
**Pull request by Guekka**
Front office CSS for displaying image still needs to be done @Apoorva64 
I suck at CSS

### CODE REVIEW

**Comment by Apoorva64** [comment]
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 070dd52f2fb1b44899d4840b6a900345f022a301. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=640ee8fb56da4d6500e89717&branchName=331,330-change-quiz-title-and-image)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`nx serve backend-api`](https://cloud.nx.app/runs/g8XYIfKIPu)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

**Comment by Apoorva64** [comment]
> Front office CSS for displaying image still needs to be done @Apoorva64 I suck at CSS

@ozeliurs is up ask him

**Comment by Guekka** [comment]
@ozeliurs I summon you

**Comment by ozeliurs** [comment]
@Apoorva64 @Guekka this seems to be ready

**Review by ozeliurs — APPROVED** [review]

**Pull request merged**
